version: '3.7'

services:

  postgres:
    container_name: 
    image: postgres
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports: 
      - ""

  pgadmin4:
    container_name: 
    image: dpage/pgadmin4
    environment:
       PGADMIN_DEFAULT_EMAIL: 
       PGADMIN_DEFAULT_PASSWORD: 
    ports:
     - ""

  